version: "3.8"

services:
  redis:
    image: redis:7.0-bullseye
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - public
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  public:
    name: public

