version: "3.8"

services:
  webapp:
    container_name: webapp
    extends:
      file: common-services.yml
      service: base
    environment:
      - REDIS_HOST=redis
    command: /src/boot.sh
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: redis:6
    container_name: redis
    extends:
      file: common-services.yml
      service: logs

