global:
  scrape_interval: 5s
  external_labels:
    namespace: local

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          container: 'prometheus'

  - job_name: kafka-exporter
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]
        labels:
          container: 'kafka-exporter'

