version: '3.7'

services:
  spark-master:
    image: bitnami/spark:${SPARK_VERSION:-latest}
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - ./workspace/data.txt:/src/data.txt
      - ./workspace/application.py:/src/application.py
    networks:
      - quick-starts
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  spark-worker-1:
    image: bitnami/spark:${SPARK_VERSION:-latest}
    container_name: spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      spark-master:
        condition: service_started
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports: 
      - 8081:8081
    networks:
      - quick-starts
    volumes:
      - ./workspace/data.txt:/src/data.txt
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
 
  spark-worker-2:
    image: bitnami/spark:${SPARK_VERSION:-latest}
    container_name: spark-worker-2
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      spark-master:
        condition: service_started
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - 8082:8081
    networks:
      - quick-starts
    volumes:
      - ./workspace/data.txt:/src/data.txt
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  quick-starts:
    name: quick-starts
