version: '3.8'

services:
 zookeeper:
   image: confluentinc/cp-zookeeper:7.3.0
   hostname: zookeeper
   container_name: zookeeper
   environment:
     ZOOKEEPER_SERVER_ID: 1
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000
   networks:
     - kafka-network
   logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

 kafka-broker:
   image: confluentinc/cp-kafka:7.3.0
   hostname: kafka-broker
   container_name: kafka-broker
   ports:
     - 29092:29092
     - 9092:9092
     - 9101:9101
   depends_on:
     - zookeeper
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker:29092,EXTERNAL://localhost:9092 # internal (kafka-broker:29092) external (localhost:9092)
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
     KAFKA_JMX_PORT: 9101
     KAFKA_JMX_HOSTNAME: localhost
   networks:
     - kafka-network
   healthcheck:
      test: nc -vz localhost 9092
      interval: 10s
      timeout: 10s
      retries: 3
   logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  kafka-network:
    name: kafka-network
