version: '3.8'

services:
 zookeeper:
   image: confluentinc/cp-zookeeper:7.3.0
   hostname: zookeeper
   container_name: zookeeper
   environment:
     ZOOKEEPER_SERVER_ID: 1
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000
   networks:
     - kafka-network

 kafka-broker:
   image: confluentinc/cp-kafka:7.3.0
   hostname: kafka-broker
   container_name: kafka-broker
   ports:
     - 29092:29092
     - 9092:9092
     - 9101:9101
   depends_on:
     - zookeeper
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
     KAFKA_JMX_PORT: 9101
     KAFKA_JMX_HOSTNAME: localhost
   networks:
     - kafka-network

networks:
  kafka-network:
    name: kafka-network
