version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - quickstarts
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  publisher:
    build: ./publisher
    container_name: publisher
    restart: unless-stopped
    volumes:
      - ./publisher:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - quickstarts
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  consumer:
    build: ./consumer
    container_name: consumer
    restart: unless-stopped
    volumes:
      - ./consumer:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - quickstarts
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  quickstarts:
    name: quickstarts
